name: democracy-hackathon
channels:
  - conda-forge
  - defaults
dependencies:
  - bzip2=1.0.6=h1de35cc_1002
  - ca-certificates=2019.6.16=hecc5488_0
  - certifi=2019.6.16=py37_0
  - cycler=0.10.0=py_1
  - freetype=2.10.0=h24853df_0
  - joblib=0.13.2=py_0
  - kiwisolver=1.1.0=py37h770b8ee_0
  - libblas=3.8.0=10_openblas
  - libcblas=3.8.0=10_openblas
  - libcxx=8.0.0=4
  - libcxxabi=8.0.0=4
  - libffi=3.2.1=h6de7cb9_1006
  - libgfortran=3.0.1=0
  - liblapack=3.8.0=10_openblas
  - libopenblas=0.3.6=hd44dcd8_4
  - libpng=1.6.37=h2573ce8_0
  - lightgbm=2.2.1=py37he6710b0_0
  - llvm-openmp=8.0.0=h770b8ee_0
  - matplotlib=3.1.1=py37_0
  - matplotlib-base=3.1.1=py37h3a684a6_0
  - ncurses=6.1=h0a44026_1002
  - numpy=1.16.4=py37h6b0580a_0
  - openblas=0.3.6=hd44dcd8_4
  - openssl=1.1.1c=h01d97ff_0
  - pandas=0.24.2=py37h86efe34_0
  - patsy=0.5.1=py_0
  - pip=19.1.1=py37_0
  - pyparsing=2.4.0=py_0
  - python=3.7.3=h93065d6_1
  - python-dateutil=2.8.0=py_0
  - pytz=2019.1=py_0
  - readline=8.0=hcfe32e1_0
  - scikit-learn=0.21.2=py37hd4ffd6c_1
  - scipy=1.3.0=py37hab3da7d_0
  - seaborn=0.9.0=py_1
  - setuptools=41.0.1=py37_0
  - six=1.12.0=py37_1000
  - sqlite=3.29.0=hb7d70f7_0
  - statsmodels=0.10.0=py37heacc8b8_0
  - tk=8.6.9=h2573ce8_1002
  - tornado=6.0.3=py37h01d97ff_0
  - wheel=0.33.4=py37_0
  - xz=5.2.4=h1de35cc_1001
  - zlib=1.2.11=h1de35cc_1004
  - pip:
    - atomicwrites==1.3.0
    - attrs==19.1.0
    - chardet==3.0.4
    - idna==2.8
    - importlib-metadata==0.18
    - maven==0.0.6
    - more-itertools==7.1.0
    - packaging==19.0
    - pluggy==0.12.0
    - py==1.8.0
    - pytest==5.0.1
    - requests==2.22.0
    - urllib3==1.25.3
    - wcwidth==0.1.7
    - xlrd==1.2.0
    - zipp==0.5.2
